openapi: "3.0.0"

info:
  version: 1.0.0
  title: Authentication
  description: All Videa APIs require an authorization token which is passed in the header of every client request. To obtain the authorization token, clients must first authenticate using their clientId and clientSecret which can be obtained from Videa support.
  termsOfService: https://videa.tv/visitor/
  contact:
    name: Videa API
    email: apidocs@videa.tv
    url: https://videa.tv/
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.videa.tv

paths:
  /v1/auth/:
    post:
      summary: Authenticate and receive an authorization token
      description: Authenticate and receive an authorization token
      requestBody:
        description: uploadInventory
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: 'schemas/authenticationSchemas.yaml#/components/schemas/requestAuthToken'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/authenticationSchemas.yaml#/components/schemas/jwtAccessToken'
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'