openapi: "3.0.0"

info:
  version: 1.0.0
  title: Authentication
  description: All Videa APIs require an authorization token which is passed in the header of every client request. To obtain the authorization token, clients must first authenticate using their clientId and clientSecret which can be obtained from Videa support.
  termsOfService: https://videa.tv/visitor/
  contact:
    name: Videa API
    email: apidocs@videa.tv
    url: https://videa.tv/
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.videa.tv

paths:
  /v1/auth/clientId/{clientId}/clientSecret/{clientSecret}/grantType/{grantType}/scope/{scope}:
    post:
      summary: Authenticate and receive an authorization token
      description: Authenticate and receive an authorization token
      parameters:
        - name: clientId
          in: path
          description: The id of the client that will perform requests, obtained through Videa website or from Videa support
          required: true
        - name: clientSecret
          in: path
          description: The client secret, obtained through Videa website or from Videa support
          required: true
        - name: grantType
          in: path
          description: Specify client_credentials
          required: true
        - name: scope
          in: path
          description: Resource name of the APIs the client is requesting access to
          required: true
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/authenticationSchemas'
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'